Update Jekyll version and pin Ruby version
Dealing with a problem where the devcontainer won't launch due to erros
like:
```
marenster.github.io/vendor/bundle/ruby/3.2.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:266:in `search_up': undefined method `untaint' for "/Users/charles/dev/marenster.github.io":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
```